var SONGLIST = [
    "Wiz Khalifa - See You Again",
   	"Mark Ronson - Uptown Funk",
   	"Justin Bieber - Sorry",
   	"Maroon 5 - Sugar",
   	"Taylor Swift - Shake It Off",
   	"Katy Perry - Roar",
   	"Enrique Iglesias - Bailando",
   	"Ed Sheeran - Thinking Out Loud",
   	"Katy Perry - Dark Horse",
   	"Major Lazer & DJ Snake - Lean On",
   	"OneRepublic - Counting Stars",
   	"Taylor Swift - Blank Space",
   	"The Chainsmokers - Closer",
   	"Calvin Harris - This Is What You Came For",
   	"Justin Bieber - What Do You Mean?",
   	"Clean Bandit - Rockabye",
   	"Alan Walker - Faded",
   	"Ellie Goulding - Love Me Like You Do",
   	"Avicii - Wake Me Up",
   	"Fifth Harmony - Worth It",
   	"Eminem - Love The Way You Lie",
   	"Silent6 - Watch Me",
   	"LMFAO - Party Rock Anthem",
   	"J. Balvin - Ay Vamos",
   	"Drake - Hotline Bling",
   	"twenty one pilots - Stressed Out",
   	"Adele - Rolling in the Deep",
   	"Ellie Goulding - Burn",
   	"Jennifer Lopez - On The Floor",
   	"The Weeknd - The Hills",
   	"Calvin Harris - Summer",
   	"Taylor Swift - Bad Blood",
   	"Rihanna - Diamonds",
   	"Martin Garrix - Animals",
   	"PSY - GENTLEMAN",
   	"Bruno Mars - Just The Way You Are",
   	"Ariana Grande - Problem",
   	"Katy Perry - Firework",
   	"Carly Rae Jepsen - Call Me Maybe",
   	"Ricky Martin - La Mordidita",
   	"The Chainsmokers - Don't Let Me Down",
   	"twenty one pilots - Heathens",
   	"Pharrell Williams - Happy",
   	"Shawn Mendes - Stitches",
   	"Rihanna - Work",
   	"Don Omar - Danza Kuduro",
   	"Shakira - La La La",
   	"J Balvin - 6 AM",
   	"Ariana Grande - Break Free",
   	"Imagine Dragons - Radioactive",
   	"The Weeknd - Can't Feel My Face",
   	"Marshmello - Alone"
];

module.exports = SONGLIST;